## Estructuras de datos. Librería Pandas (II)

![logo](img/pandas-logo.png)

# Operaciones en pandas
- Búsqueda
- Ordenar
- Operaciones matemáticas entre objetos
- apply(lambda)
- Estadística descriptiva
- Ejemplo fuel efficiency

#### Búsqueda

In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  4  3  1
1  0  0  1

In [4]:
# buscando columnas (DataFrame como dic, busca en claves)
# Hacemos uso de 'in' para localizar la columna 'A' en el dataframe
'A' in frame

True

In [5]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False   True  False
1  False  False  False

In [6]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0   True  False  False
1  False  False  False

numpy.ndarray

In [7]:
# Cuántos valores son >= 4
mask = frame >= 4
print(mask.values.sum())
display(mask)

1

       A      B      C
0   True  False  False
1  False  False  False

#### Ordenación

In [8]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=list('DACB'),index=indices)
display(frame)

    D   A   C   B
1   1   6  15  14
4  11   5  12   2
0  19   3  10   3
2   4   1   8  18
3   9  19   5   3

In [9]:
# ordenar por índice
display(frame.sort_index(ascending=False))

    D   A   C   B
4  11   5  12   2
3   9  19   5   3
2   4   1   8  18
1   1   6  15  14
0  19   3  10   3

In [10]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=True))

    A   B   C   D
1   6  14  15   1
4   5   2  12  11
0   3   3  10  19
2   1  18   8   4
3  19   3   5   9

In [11]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=False))

    D   A   C   B
3   9  19   5   3
1   1   6  15  14
4  11   5  12   2
0  19   3  10   3
2   4   1   8  18

In [12]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=0, axis=1, ascending=False))

    D   C   A   B
1   1  15   6  14
4  11  12   5   2
0  19  10   3   3
2   4   8   1  18
3   9   5  19   3

In [13]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
3   9  19   5   3
1   1   6  15  14
4  11   5  12   2
0  19   3  10   3
2   4   1   8  18

#### Ranking
- Construir un ranking de valores

In [14]:
display(frame.rank(method='average'))

     D    A    C    B
3  3.0  5.0  1.0  2.5
1  1.0  4.0  5.0  4.0
4  4.0  3.0  4.0  1.0
0  5.0  2.0  3.0  2.5
2  2.0  1.0  2.0  5.0

In [15]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

15
12
10
8
5

# Operaciones

Operaciones matemáticas entre objetos

In [16]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  84  17  11  40
1  89  67  29  63
2  37  88  79  37
3  27  39  17  45

    0   1   2   3
0  73  73  31  94
1  36  43  65  44
2  15  31  91  36
3  73  11  96  47

In [17]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display (frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0  157   90   42  134
1  125  110   94  107
2   52  119  170   73
3  100   50  113   92

     0    1    2    3
0  157   90   42  134
1  125  110   94  107
2   52  119  170   73
3  100   50  113   92

In [18]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -11  56  20  54
1 -53 -24  36 -19
2 -22 -57  12  -1
3  46 -28  79   2

    0   1   2   3
0 -11  56  20  54
1 -53 -24  36 -19
2 -22 -57  12  -1
3  46 -28  79   2

In [19]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameA + frameC)

    0   1   2   3
0  84  17  11  40
1  89  67  29  63
2  37  88  79  37
3  27  39  17  45

    0   1   2
0  93  98  90
1   5  65  52
2  46  84  30

       0      1      2   3
0  177.0  115.0  101.0 NaN
1   94.0  132.0   81.0 NaN
2   83.0  172.0  109.0 NaN
3    NaN    NaN    NaN NaN

In [20]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.sub(frameC,fill_value=0))

      0     1     2     3
0  -9.0 -81.0 -79.0  40.0
1  84.0   2.0 -23.0  63.0
2  -9.0   4.0  49.0  37.0
3  27.0  39.0  17.0  45.0

Operadores aritméticos solo válidos en elementos aceptables

In [21]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [22]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
# # Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  0  4  4  5
1  7  7  4  1
2  7  4  9  4

pandas.Series

   A  B  C  D
0  0  0  0  0
1  7  3  0 -4
2  7  0  5 -1

   A  B  C  D
0  0  4  4  5
1  0  0 -3 -6
2  0 -3  2 -3

pandas se basa en NumPy, np operadores binarios y unarios son aceptables 

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [23]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min())) # diferencia por columna

   A  B  C  D
0  1  4  8  3
1  1  3  7  0
2  2  0  5  8

A    1
B    4
C    3
D    8
dtype: int64

In [24]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  4  6  0  2
1  2  9  7  0
2  2  1  7  0

0    6
1    9
2    7
dtype: int64

# Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame

In [25]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30], 
               "puntos" : [98,12,98,40], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe(include='all')) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34      98      F
1   Laura    34      12      F
2  Manuel    11      98      M
3  Carlos    30      40      M

        nombre       edad     puntos genero
count        4   4.000000   4.000000      4
unique       4        NaN        NaN      2
top     Marisa        NaN        NaN      F
freq         1        NaN        NaN      2
mean       NaN  27.250000  62.000000    NaN
std        NaN  10.996211  43.112257    NaN
min        NaN  11.000000  12.000000    NaN
25%        NaN  25.250000  33.000000    NaN
50%        NaN  32.000000  69.000000    NaN
75%        NaN  34.000000  98.000000    NaN
max        NaN  34.000000  98.000000    NaN

In [26]:
print(type(frame['edad']))

<class 'pandas.Series'>

In [27]:
# operadores básicos
frame.sum()

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                        248
genero                       FFMM
dtype: object

In [28]:
frame.drop(['nombre','genero'],axis=1).mean() #Eliminamos las columnas con contenido "incompatible" con la media

edad      27.25
puntos    62.00
dtype: float64

In [29]:
frame.cumsum() #suma acumulativa

                    nombre  edad  puntos genero
0                   Marisa    34      98      F
1              MarisaLaura    68     110     FF
2        MarisaLauraManuel    79     208    FFM
3  MarisaLauraManuelCarlos   109     248   FFMM

In [30]:
frame.count()

nombre    4
edad      4
puntos    4
genero    4
dtype: int64

In [31]:
frame['edad'].std()

np.float64(10.996211468804457)

In [32]:
frame['edad'].idxmax() # índice del elemento con valor máximo para la edad

0

In [33]:
frame['puntos'].idxmin()

1

In [34]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98

   nombre  edad  puntos genero
0  Marisa    34      98      F
2  Manuel    11      98      M

pandas incluye métodos para analizar correlaciones
- Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2) --> medida de correlación entre los datos de ambos objetos
- https://www.datascience.com/blog/introduction-to-correlation-learn-data-science-tutorials

Correlación

In [35]:
x = pd.Series(range(10,20))
y = pd.Series([2,1,4,5,8,12,18,25,96,48])
print("Correlación de x sobre y: ", x.corr(y)) # por defecto, se usa el coeficiente de correlación de Pearson
print("Correlación de y sobre x: ", y.corr(x))

Correlación de x sobre y:  0.7586402890911867
Correlación de y sobre x:  0.7586402890911869

In [36]:
print("Correlación de x sobre y (Rho Spearman): ", x.corr(y, method='spearman'))
print("Correlación de x sobre y (Tau Kendall): ", x.corr(y, method='kendall'))

Correlación de x sobre y (Rho Spearman):  0.9757575757575757
Correlación de x sobre y (Tau Kendall):  0.911111111111111

## Agregaciones

In [37]:
display(frame)
display(frame.groupby('genero').count())  # agrupar primero y aplicar operación después.

   nombre  edad  puntos genero
0  Marisa    34      98      F
1   Laura    34      12      F
2  Manuel    11      98      M
3  Carlos    30      40      M

        nombre  edad  puntos
genero
F            2     2       2
M            2     2       2

In [38]:
display(frame.drop('nombre',axis=1).groupby('genero').mean())  # eliminamos primero la columna de datos que no podemos operar

        edad  puntos
genero
F       34.0    55.0
M       20.5    69.0

In [39]:
display(frame.groupby('genero').max())

        nombre  edad  puntos
genero
F       Marisa    34      98
M       Manuel    30      98

In [40]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', np.median, max]))

       edad            puntos
        min median max    min median max
genero
F        34   34.0  34     12   55.0  98
M        11   20.5  30     40   69.0  98

In [41]:
# Filtrado de los datos en el que el conjunto no supera una media determinada 
def media(x):
    return x["edad"].mean() > 30

frame.groupby('genero').filter(media)

   nombre  edad  puntos genero
0  Marisa    34      98      F
1   Laura    34      12      F

## Pivot Table
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
- https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

In [42]:
# Ejemplo de uso de pivot-table en Pandas
import pandas as pd
import numpy as np

In [44]:
df = pd.read_excel("./datasets/sales-funnel.xlsx") # debemos instalar 'openpyxl' para poder acceder al fichero xlsx
df.head()

,Account,Name,Rep,Manager,Product,Quantity,Price,Status
0,714466,Trantow-Barrows,Craig Booker,Debra Henley,CPU,1,30000,presented
1,714466,Trantow-Barrows,Craig Booker,Debra Henley,Software,1,10000,presented
2,714466,Trantow-Barrows,Craig Booker,Debra Henley,Maintenance,2,5000,pending
3,737550,"Fritsch, Russel and Anderson",Craig Booker,Debra Henley,CPU,1,35000,declined
4,146832,Kiehn-Spinka,Daniel Hilton,Debra Henley,CPU,2,65000,won

In [45]:
df["Status"] = df["Status"].astype("category")
df["Status"]=df["Status"].cat.set_categories(["won","pending","presented","declined"])

In [46]:
pd.pivot_table(df,index=["Name"],values=["Account","Price","Quantity"], aggfunc="mean") # el parámetro "aggfunc" nos indica la función de agregación usada (sumatorio, media,...)

                               Account     Price  Quantity
Name
Barton LLC                    740150.0   35000.0  1.000000
Fritsch, Russel and Anderson  737550.0   35000.0  1.000000
Herman LLC                    141962.0   65000.0  2.000000
Jerde-Hilpert                 412290.0    5000.0  2.000000
Kassulke, Ondricka and Metz   307599.0    7000.0  3.000000
Keeling LLC                   688981.0  100000.0  5.000000
Kiehn-Spinka                  146832.0   65000.0  2.000000
Koepp Ltd                     729833.0   35000.0  2.000000
Kulas Inc                     218895.0   25000.0  1.500000
Purdy-Kunde                   163416.0   30000.0  1.000000
Stokes LLC                    239344.0    7500.0  1.000000
Trantow-Barrows               714466.0   15000.0  1.333333

In [47]:
pd.pivot_table(df,index=["Name","Rep","Manager"], values=["Account","Price","Quantity"], aggfunc="mean")

,,,Account,Price,Quantity
Name,Rep,Manager,,,
Barton LLC,John Smith,Debra Henley,740150.0,35000.0,1.000000
"Fritsch, Russel and Anderson",Craig Booker,Debra Henley,737550.0,35000.0,1.000000
Herman LLC,Cedric Moss,Fred Anderson,141962.0,65000.0,2.000000
Jerde-Hilpert,John Smith,Debra Henley,412290.0,5000.0,2.000000
"Kassulke, Ondricka and Metz",Wendy Yule,Fred Anderson,307599.0,7000.0,3.000000
Keeling LLC,Wendy Yule,Fred Anderson,688981.0,100000.0,5.000000
Kiehn-Spinka,Daniel Hilton,Debra Henley,146832.0,65000.0,2.000000
Koepp Ltd,Wendy Yule,Fred Anderson,729833.0,35000.0,2.000000
Kulas Inc,Daniel Hilton,Debra Henley,218895.0,25000.0,1.500000
Purdy-Kunde,Cedric Moss,Fred Anderson,163416.0,30000.0,1.000000
Stokes LLC,Cedric Moss,Fred Anderson,239344.0,7500.0,1.000000
Trantow-Barrows,Craig Booker,Debra Henley,714466.0,15000.0,1.333333

In [48]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Account","Price","Quantity"], aggfunc="mean")

                              Account         Price  Quantity
Manager       Rep
Debra Henley  Craig Booker   720237.0  20000.000000  1.250000
              Daniel Hilton  194874.0  38333.333333  1.666667
              John Smith     576220.0  20000.000000  1.500000
Fred Anderson Cedric Moss    196016.5  27500.000000  1.250000
              Wendy Yule     614061.5  44250.000000  3.000000

# Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

Consumo de combustible (*Miles Per Gallon*)

In [18]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, delim_whitespace=True, header=None,
            names = ['mpg', 'cilindros', 'desplazamiento','potencia',
            'peso', 'aceleracion', 'año', 'origen', 'nombre'],
            na_values='?')

In [19]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
20,25.0,4,110.0,87.0,2672.0,17.5,70,2,peugeot 504
169,20.0,6,232.0,100.0,2914.0,16.0,75,1,amc gremlin
395,32.0,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage
199,20.0,6,225.0,100.0,3651.0,17.7,76,1,dodge aspen se
226,20.5,6,231.0,105.0,3425.0,16.9,77,1,buick skylark

In [20]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [21]:
mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB

### Correlaciones entre valores

In [22]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

-0.8317409332443351

In [23]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

-0.4174573199403932

### Correlaciones entre todos los valores

In [26]:
mpg_data.drop(['nombre'],axis=1).corr()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [29]:
#año y origen no parecen correlacionables. Evidentemente, el nombre tampoco es correlacionales y, como en el apartado anterior, también lo eliminamos
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen','nombre'],axis=1).corr()
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [30]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [31]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [33]:
# correlación más negativa
mpg_data.drop(['año','origen','nombre'],axis=1).corr().idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: object

In [34]:
# correlación más positiva
mpg_data.drop(['año','origen','nombre'],axis=1).corr().idxmax()  #consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: object

In [35]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen','nombre'],axis=1).corr()
np.fill_diagonal(positive_corr.values, 0)
# display(positive_corr)
positive_corr.idxmax()

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: object

In [36]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

## <img src="img/by-nc.png" width="200">