# ONE HOT ENCODING

In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('./datasets/Employee.csv')
encoded_data = pd.get_dummies(data[ 'Gender'])

In [5]:
encoded_data

      Female   Male
0      False   True
1       True  False
2       True  False
3      False   True
4      False   True
...      ...    ...
4648    True  False
4649   False   True
4650   False   True
4651   False   True
4652   False   True

[4653 rows x 2 columns]

In [6]:
data= data.join(encoded_data)
data.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Female,Male
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,False,True
1,Bachelors,2013,Pune,1,28,Female,No,3,1,True,False
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,True,False
3,Masters,2016,Bangalore,3,27,Male,No,5,1,False,True
4,Masters,2017,Pune,3,24,Male,Yes,2,1,False,True

In [7]:
data.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Female,Male
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,False,True
1,Bachelors,2013,Pune,1,28,Female,No,3,1,True,False
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,True,False
3,Masters,2016,Bangalore,3,27,Male,No,5,1,False,True
4,Masters,2017,Pune,3,24,Male,Yes,2,1,False,True

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
onehotencoder = OneHotEncoder()
data['Gender']= data['Gender'].fillna(data['Gender'].mode()[0])

In [12]:
onehotencoder.fit_transform(data[['Gender']]).toarray()

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], shape=(4653, 2))

# LABEL ENCODING

In [14]:
import pandas as pd

In [24]:
data = pd.read_csv('./datasets/Employee.csv')
from sklearn.preprocessing import LabelEncoder, label_binarize

label_encoder = LabelEncoder()


encoded_data =pd.DataFrame(label_encoder.fit_transform(data["EverBenched"]),columns=["EBTransformed"])

print(encoded_data)

      EBTransformed
0                 0
1                 0
2                 0
3                 0
4                 1
...             ...
4648              0
4649              0
4650              0
4651              1
4652              1

[4653 rows x 1 columns]

In [25]:
data_encoded = data.join(encoded_data)

print(data_encoded)

      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No
1     Bachelors         2013       Pune            1   28  Female          No
2     Bachelors         2014  New Delhi            3   38  Female          No
3       Masters         2016  Bangalore            3   27    Male          No
4       Masters         2017       Pune            3   24    Male         Yes
...         ...          ...        ...          ...  ...     ...         ...
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot  EBTransformed
0                             0           0              0
1                             3           1              0
2                             2           0              0
3                             5           1              0
4                             2           1              1
...                         ...         ...            ...
4648                          4           0              0
4649                          2           1              0
4650                          5           1              0
4651                          2           0              1
4652                          4           0              1

[4653 rows x 10 columns]

# PANDAS -> getDummies()

In [1]:
import pandas as pd

df = pd.DataFrame({
    "color": [
        "Rojo",
        "Azul",
        "Verde",
        "Rojo"
    ]
})

df_encoded = pd.get_dummies(
    df,
    columns=["color"]
)

print(df_encoded)

   color_Azul  color_Rojo  color_Verde
0       False        True        False
1        True       False        False
2       False       False         True
3       False        True        False

# SCIKIT-LEARN -> One Hot Encoder (OHE)

In [3]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
X=df[["color"]]

X_encoded = encoder.fit_transform(X)

In [4]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoder.fit(X)

print(
    encoder.get_feature_names_out()
)

['color_Azul' 'color_Rojo' 'color_Verde']

## Buenas Prácticas
- Aplicarlo únicamente a variables categóricas nominales.
- Evaluar la cardinalidad de las categorías antes de codificar.
- Considerar técnicas alternativas para variables con miles de categorías.
- Integrar la transformación dentro de un Pipeline.
- Ajustar el codificador únicamente con los datos de entrenamiento.
- Revisar el impacto sobre la dimensionalidad del conjunto de datos.